# Generated by Django 4.1.7 on 2023-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completing_step",
            field=models.CharField(
                choices=[("0", "To Do"), ("1", "Doing"), ("2", "Done")], max_length=1
            ),
        ),
    ]
